services:
  brindeflow-site:
    image: nginx:alpine
    container_name: brindeflow-site
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: always
